/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calculadoralab1;

import java.awt.Color;



/**
 *
 * @author Sebas
 */
public class InterfazCalculadora extends javax.swing.JFrame {
Operaciones ope = new Operaciones();//Instanciar

    public double numero1;  
    public double anguloEnRadianes;
    
    
    
    public InterfazCalculadora() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Boton7 = new javax.swing.JButton();
        Boton8 = new javax.swing.JButton();
        Boton9 = new javax.swing.JButton();
        BotonDelete = new javax.swing.JButton();
        BotonSen = new javax.swing.JButton();
        BotonTan = new javax.swing.JButton();
        Boton4 = new javax.swing.JButton();
        Boton5 = new javax.swing.JButton();
        Boton6 = new javax.swing.JButton();
        BotonMenos = new javax.swing.JButton();
        BotonCos = new javax.swing.JButton();
        BotonMultip = new javax.swing.JButton();
        Boton1 = new javax.swing.JButton();
        Boton2 = new javax.swing.JButton();
        Boton3 = new javax.swing.JButton();
        Boton2Ceros = new javax.swing.JButton();
        Boton0 = new javax.swing.JButton();
        Pi = new javax.swing.JButton();
        BotonSqrt = new javax.swing.JButton();
        BotonDivision = new javax.swing.JButton();
        BotonIva = new javax.swing.JButton();
        BotonMas = new javax.swing.JButton();
        BotonResultado = new javax.swing.JButton();
        BotonClear = new javax.swing.JButton();
        BotonPow = new javax.swing.JButton();
        Pantalla = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        Boton7.setBackground(new java.awt.Color(0, 153, 153));
        Boton7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Boton7.setForeground(new java.awt.Color(255, 255, 255));
        Boton7.setText("7");
        Boton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Boton7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Boton7MouseExited(evt);
            }
        });
        Boton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton7ActionPerformed(evt);
            }
        });

        Boton8.setBackground(new java.awt.Color(0, 153, 153));
        Boton8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Boton8.setForeground(new java.awt.Color(255, 255, 255));
        Boton8.setText("8");
        Boton8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Boton8MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Boton8MouseExited(evt);
            }
        });
        Boton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton8ActionPerformed(evt);
            }
        });

        Boton9.setBackground(new java.awt.Color(0, 153, 153));
        Boton9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Boton9.setForeground(new java.awt.Color(255, 255, 255));
        Boton9.setText("9");
        Boton9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Boton9MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Boton9MouseExited(evt);
            }
        });
        Boton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton9ActionPerformed(evt);
            }
        });

        BotonDelete.setBackground(new java.awt.Color(0, 153, 153));
        BotonDelete.setForeground(new java.awt.Color(255, 255, 255));
        BotonDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calculadoralab1/delete-text (1).png"))); // NOI18N
        BotonDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotonDeleteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BotonDeleteMouseExited(evt);
            }
        });
        BotonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonDeleteActionPerformed(evt);
            }
        });

        BotonSen.setBackground(new java.awt.Color(0, 153, 153));
        BotonSen.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        BotonSen.setForeground(new java.awt.Color(255, 255, 255));
        BotonSen.setText("Sen");
        BotonSen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotonSenMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BotonSenMouseExited(evt);
            }
        });
        BotonSen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonSenActionPerformed(evt);
            }
        });

        BotonTan.setBackground(new java.awt.Color(0, 153, 153));
        BotonTan.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        BotonTan.setForeground(new java.awt.Color(255, 255, 255));
        BotonTan.setText("Tan");
        BotonTan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotonTanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BotonTanMouseExited(evt);
            }
        });
        BotonTan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonTanActionPerformed(evt);
            }
        });

        Boton4.setBackground(new java.awt.Color(0, 153, 153));
        Boton4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Boton4.setForeground(new java.awt.Color(255, 255, 255));
        Boton4.setText("4");
        Boton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Boton4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Boton4MouseExited(evt);
            }
        });
        Boton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton4ActionPerformed(evt);
            }
        });

        Boton5.setBackground(new java.awt.Color(0, 153, 153));
        Boton5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Boton5.setForeground(new java.awt.Color(255, 255, 255));
        Boton5.setText("5");
        Boton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Boton5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Boton5MouseExited(evt);
            }
        });
        Boton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton5ActionPerformed(evt);
            }
        });

        Boton6.setBackground(new java.awt.Color(0, 153, 153));
        Boton6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Boton6.setForeground(new java.awt.Color(255, 255, 255));
        Boton6.setText("6");
        Boton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Boton6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Boton6MouseExited(evt);
            }
        });
        Boton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton6ActionPerformed(evt);
            }
        });

        BotonMenos.setBackground(new java.awt.Color(0, 153, 153));
        BotonMenos.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        BotonMenos.setForeground(new java.awt.Color(255, 255, 255));
        BotonMenos.setText("-");
        BotonMenos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotonMenosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BotonMenosMouseExited(evt);
            }
        });
        BotonMenos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonMenosActionPerformed(evt);
            }
        });

        BotonCos.setBackground(new java.awt.Color(0, 153, 153));
        BotonCos.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        BotonCos.setForeground(new java.awt.Color(255, 255, 255));
        BotonCos.setText("Cos");
        BotonCos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotonCosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BotonCosMouseExited(evt);
            }
        });
        BotonCos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonCosActionPerformed(evt);
            }
        });

        BotonMultip.setBackground(new java.awt.Color(0, 153, 153));
        BotonMultip.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        BotonMultip.setForeground(new java.awt.Color(255, 255, 255));
        BotonMultip.setText("x");
        BotonMultip.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotonMultipMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BotonMultipMouseExited(evt);
            }
        });
        BotonMultip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonMultipActionPerformed(evt);
            }
        });

        Boton1.setBackground(new java.awt.Color(0, 153, 153));
        Boton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Boton1.setForeground(new java.awt.Color(255, 255, 255));
        Boton1.setText("1");
        Boton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Boton1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Boton1MouseExited(evt);
            }
        });
        Boton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton1ActionPerformed(evt);
            }
        });

        Boton2.setBackground(new java.awt.Color(0, 153, 153));
        Boton2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Boton2.setForeground(new java.awt.Color(255, 255, 255));
        Boton2.setText("2");
        Boton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Boton2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Boton2MouseExited(evt);
            }
        });
        Boton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton2ActionPerformed(evt);
            }
        });

        Boton3.setBackground(new java.awt.Color(0, 153, 153));
        Boton3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Boton3.setForeground(new java.awt.Color(255, 255, 255));
        Boton3.setText("3");
        Boton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Boton3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Boton3MouseExited(evt);
            }
        });
        Boton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton3ActionPerformed(evt);
            }
        });

        Boton2Ceros.setBackground(new java.awt.Color(0, 153, 153));
        Boton2Ceros.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Boton2Ceros.setForeground(new java.awt.Color(255, 255, 255));
        Boton2Ceros.setText("00");
        Boton2Ceros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Boton2CerosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Boton2CerosMouseExited(evt);
            }
        });
        Boton2Ceros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton2CerosActionPerformed(evt);
            }
        });

        Boton0.setBackground(new java.awt.Color(0, 153, 153));
        Boton0.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Boton0.setForeground(new java.awt.Color(255, 255, 255));
        Boton0.setText("0");
        Boton0.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Boton0MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Boton0MouseExited(evt);
            }
        });
        Boton0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton0ActionPerformed(evt);
            }
        });

        Pi.setBackground(new java.awt.Color(0, 153, 153));
        Pi.setForeground(new java.awt.Color(255, 255, 255));
        Pi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calculadoralab1/mathematics (1) (1).png"))); // NOI18N
        Pi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PiMouseExited(evt);
            }
        });
        Pi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PiActionPerformed(evt);
            }
        });

        BotonSqrt.setBackground(new java.awt.Color(0, 153, 153));
        BotonSqrt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calculadoralab1/square-root (2) (1).png"))); // NOI18N
        BotonSqrt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotonSqrtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BotonSqrtMouseExited(evt);
            }
        });
        BotonSqrt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonSqrtActionPerformed(evt);
            }
        });

        BotonDivision.setBackground(new java.awt.Color(0, 153, 153));
        BotonDivision.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        BotonDivision.setForeground(new java.awt.Color(255, 255, 255));
        BotonDivision.setText("/");
        BotonDivision.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotonDivisionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BotonDivisionMouseExited(evt);
            }
        });
        BotonDivision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonDivisionActionPerformed(evt);
            }
        });

        BotonIva.setBackground(new java.awt.Color(0, 153, 153));
        BotonIva.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        BotonIva.setForeground(new java.awt.Color(255, 255, 255));
        BotonIva.setText("Iva");
        BotonIva.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotonIvaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BotonIvaMouseExited(evt);
            }
        });
        BotonIva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonIvaActionPerformed(evt);
            }
        });

        BotonMas.setBackground(new java.awt.Color(0, 153, 153));
        BotonMas.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        BotonMas.setForeground(new java.awt.Color(255, 255, 255));
        BotonMas.setText("+");
        BotonMas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotonMasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BotonMasMouseExited(evt);
            }
        });
        BotonMas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonMasActionPerformed(evt);
            }
        });

        BotonResultado.setBackground(new java.awt.Color(0, 153, 153));
        BotonResultado.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        BotonResultado.setForeground(new java.awt.Color(255, 255, 255));
        BotonResultado.setText("=");
        BotonResultado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotonResultadoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BotonResultadoMouseExited(evt);
            }
        });
        BotonResultado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonResultadoActionPerformed(evt);
            }
        });

        BotonClear.setBackground(new java.awt.Color(0, 153, 153));
        BotonClear.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        BotonClear.setForeground(new java.awt.Color(255, 255, 255));
        BotonClear.setText("C");
        BotonClear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotonClearMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BotonClearMouseExited(evt);
            }
        });
        BotonClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonClearActionPerformed(evt);
            }
        });

        BotonPow.setBackground(new java.awt.Color(0, 153, 153));
        BotonPow.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        BotonPow.setForeground(new java.awt.Color(255, 255, 255));
        BotonPow.setText("x^y");
        BotonPow.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotonPowMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BotonPowMouseExited(evt);
            }
        });
        BotonPow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonPowActionPerformed(evt);
            }
        });

        Pantalla.setBackground(new java.awt.Color(255, 255, 255));
        Pantalla.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        Pantalla.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Pantalla.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Pantalla.setOpaque(true);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Pantalla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Boton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Boton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Boton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Boton2Ceros, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(Boton0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Boton8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Boton5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Boton2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Pi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Boton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(Boton6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(BotonMas, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(BotonMenos, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Boton9, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BotonDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(BotonMultip, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(BotonCos, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(BotonClear, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(BotonSen, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(BotonDivision, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(BotonTan, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(BotonSqrt, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(BotonIva, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(BotonPow, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(BotonResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Pantalla, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Boton7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BotonDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(Boton9, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Boton8, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Boton4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Boton5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Boton6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BotonMenos, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Boton1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Boton2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Boton3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Boton2Ceros, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(Boton0, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Pi, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(BotonMas, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(BotonDivision, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(BotonTan, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(BotonPow, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(BotonResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(67, 67, 67)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(BotonMultip, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(BotonCos, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(BotonSqrt, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(BotonClear, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(BotonSen, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(BotonIva, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(134, 134, 134))))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Boton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton8ActionPerformed
        ope.guardarNumero(8);
       Pantalla.setText(ope.getNumero());
    }//GEN-LAST:event_Boton8ActionPerformed

    private void BotonClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonClearActionPerformed
        ope.setNumero("");
        Pantalla.setText("");
    }//GEN-LAST:event_BotonClearActionPerformed

    private void Boton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton4ActionPerformed
        ope.guardarNumero(4);
       Pantalla.setText(ope.getNumero());
    }//GEN-LAST:event_Boton4ActionPerformed

    private void Boton0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton0ActionPerformed
        ope.guardarNumero(0);
       Pantalla.setText(ope.getNumero());
    }//GEN-LAST:event_Boton0ActionPerformed

    private void Boton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton1ActionPerformed
       ope.guardarNumero(1);
       Pantalla.setText(ope.getNumero());
    }//GEN-LAST:event_Boton1ActionPerformed

    private void Boton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton2ActionPerformed
        ope.guardarNumero(2);
       Pantalla.setText(ope.getNumero());
    }//GEN-LAST:event_Boton2ActionPerformed

    private void Boton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton3ActionPerformed
        ope.guardarNumero(3);
       Pantalla.setText(ope.getNumero());
    }//GEN-LAST:event_Boton3ActionPerformed

    private void Boton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton5ActionPerformed
       ope.guardarNumero(5);
       Pantalla.setText(ope.getNumero());
    }//GEN-LAST:event_Boton5ActionPerformed

    private void Boton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton6ActionPerformed
        ope.guardarNumero(6);
       Pantalla.setText(ope.getNumero());
    }//GEN-LAST:event_Boton6ActionPerformed

    private void Boton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton7ActionPerformed
        ope.guardarNumero(7);
       Pantalla.setText(ope.getNumero());
    }//GEN-LAST:event_Boton7ActionPerformed

    private void Boton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton9ActionPerformed
        ope.guardarNumero(9);
       Pantalla.setText(ope.getNumero());
    }//GEN-LAST:event_Boton9ActionPerformed

    private void Boton2CerosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton2CerosActionPerformed
       ope.guardarNumero(0);
       ope.guardarNumero(0);
       Pantalla.setText(ope.getNumero());
    }//GEN-LAST:event_Boton2CerosActionPerformed

    private void BotonMasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonMasActionPerformed
        ope.Suma(Pantalla.getText());
        Pantalla.setText("");
    }//GEN-LAST:event_BotonMasActionPerformed

    private void BotonMenosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonMenosActionPerformed
        ope.Resta(Pantalla.getText());
        Pantalla.setText("");
    }//GEN-LAST:event_BotonMenosActionPerformed

    private void BotonMultipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonMultipActionPerformed
        ope.Multiplicacion(Pantalla.getText());
        Pantalla.setText("");
    }//GEN-LAST:event_BotonMultipActionPerformed

    private void BotonDivisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonDivisionActionPerformed
        ope.Division(Pantalla.getText());
        Pantalla.setText("");
    }//GEN-LAST:event_BotonDivisionActionPerformed

    private void BotonResultadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonResultadoActionPerformed
        if(Double.toString(ope.Resultado(Pantalla.getText())) == "Infinity" || Double.toString(ope.Resultado(Pantalla.getText())) == "NaN" ){
            Pantalla.setText("ERROR DE CALCULO");
        }else
        Pantalla.setText(""+ope.Resultado(Pantalla.getText()));
        
    }//GEN-LAST:event_BotonResultadoActionPerformed

    private void BotonSenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonSenActionPerformed
       this.numero1 = Double.parseDouble(this.Pantalla.getText());
       this.anguloEnRadianes = Math.toRadians(this.numero1);    
        this.Pantalla.setText(Double.toString(Math.sin(this.anguloEnRadianes))); 
    }//GEN-LAST:event_BotonSenActionPerformed

    private void BotonCosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonCosActionPerformed
        boolean x=false;
        this.numero1 = Double.parseDouble(this.Pantalla.getText());
        for(int i=-100000; i<=100000;i++){
            if(this.numero1==90+180*i){
            x=true;
            break;   
            }           
        }
        if (x==true){
        this.Pantalla.setText("0");}
       else{
       this.anguloEnRadianes = Math.toRadians(this.numero1);    
       this.Pantalla.setText(Double.toString(Math.cos(this.anguloEnRadianes)));
        }  
    }//GEN-LAST:event_BotonCosActionPerformed

    private void BotonTanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonTanActionPerformed
        boolean x=false;
        this.numero1 = Double.parseDouble(this.Pantalla.getText());
        for(int i=-100000; i<=100000;i++){
            if(this.numero1==90+180*i){
            x=true;
            break;   
            }           
        }
        if (x==true){
        this.Pantalla.setText("ERROR CALCULO");}
       else{
       this.anguloEnRadianes = Math.toRadians(this.numero1);    
       this.Pantalla.setText(Double.toString(Math.tan(this.anguloEnRadianes)));
       
        }
    }//GEN-LAST:event_BotonTanActionPerformed

    private void BotonIvaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonIvaActionPerformed
       ope.Iva(Pantalla.getText());
        Pantalla.setText("");
    }//GEN-LAST:event_BotonIvaActionPerformed

    private void BotonSqrtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonSqrtActionPerformed
        ope.Raiz(Pantalla.getText());
        Pantalla.setText("");
    }//GEN-LAST:event_BotonSqrtActionPerformed

    private void BotonPowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonPowActionPerformed
        ope.Potencia(Pantalla.getText());
        Pantalla.setText("");
    }//GEN-LAST:event_BotonPowActionPerformed

    private void PiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PiActionPerformed
        this.Pantalla.setText(Double.toString(Math.PI));
    }//GEN-LAST:event_PiActionPerformed

    private void BotonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonDeleteActionPerformed
       String borrar = this.Pantalla.getText();
       ope.setNumero((borrar.substring(0, borrar.length()- 1)));
       this.Pantalla.setText((borrar.substring(0, borrar.length()- 1)));            
    }//GEN-LAST:event_BotonDeleteActionPerformed

    private void BotonMasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonMasMouseEntered
    BotonMas.setBackground(new Color(45, 137, 122));      
    }//GEN-LAST:event_BotonMasMouseEntered

    private void BotonResultadoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonResultadoMouseEntered
        BotonResultado.setBackground(new Color(45, 137, 122));
    }//GEN-LAST:event_BotonResultadoMouseEntered

    private void Boton7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Boton7MouseEntered
       Boton7.setBackground(new Color(45, 137, 122));
    }//GEN-LAST:event_Boton7MouseEntered

    private void Boton8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Boton8MouseEntered
        Boton8.setBackground(new Color(45, 137, 122));
    }//GEN-LAST:event_Boton8MouseEntered

    private void Boton9MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Boton9MouseEntered
        Boton9.setBackground(new Color(45, 137, 122));
    }//GEN-LAST:event_Boton9MouseEntered

    private void Boton4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Boton4MouseEntered
        Boton4.setBackground(new Color(45, 137, 122));
    }//GEN-LAST:event_Boton4MouseEntered

    private void Boton5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Boton5MouseEntered
        Boton5.setBackground(new Color(45, 137, 122));
    }//GEN-LAST:event_Boton5MouseEntered

    private void Boton6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Boton6MouseEntered
       Boton6.setBackground(new Color(45, 137, 122));
    }//GEN-LAST:event_Boton6MouseEntered

    private void Boton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Boton1MouseEntered
        Boton1.setBackground(new Color(45, 137, 122));
    }//GEN-LAST:event_Boton1MouseEntered

    private void Boton2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Boton2MouseEntered
        Boton2.setBackground(new Color(45, 137, 122));
    }//GEN-LAST:event_Boton2MouseEntered

    private void Boton3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Boton3MouseEntered
        Boton3.setBackground(new Color(45, 137, 122));
    }//GEN-LAST:event_Boton3MouseEntered

    private void Boton2CerosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Boton2CerosMouseEntered
        Boton2Ceros.setBackground(new Color(45, 137, 122));
    }//GEN-LAST:event_Boton2CerosMouseEntered

    private void Boton0MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Boton0MouseEntered
        Boton0.setBackground(new Color(45, 137, 122));
    }//GEN-LAST:event_Boton0MouseEntered

    private void PiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PiMouseEntered
        Pi.setBackground(new Color(45, 137, 122));
    }//GEN-LAST:event_PiMouseEntered

    private void BotonDeleteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonDeleteMouseEntered
        BotonDelete.setBackground(new Color(45, 137, 122));
    }//GEN-LAST:event_BotonDeleteMouseEntered

    private void BotonMenosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonMenosMouseEntered
        BotonMenos.setBackground(new Color(45, 137, 122));
    }//GEN-LAST:event_BotonMenosMouseEntered

    private void BotonClearMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonClearMouseEntered
        BotonClear.setBackground(new Color(45, 137, 122));
    }//GEN-LAST:event_BotonClearMouseEntered

    private void BotonMultipMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonMultipMouseEntered
        BotonMultip.setBackground(new Color(45, 137, 122));
    }//GEN-LAST:event_BotonMultipMouseEntered

    private void BotonDivisionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonDivisionMouseEntered
        BotonDivision.setBackground(new Color(45, 137, 122));
    }//GEN-LAST:event_BotonDivisionMouseEntered

    private void BotonSenMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonSenMouseEntered
        BotonSen.setBackground(new Color(45, 137, 122));
    }//GEN-LAST:event_BotonSenMouseEntered

    private void BotonCosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonCosMouseEntered
        BotonCos.setBackground(new Color(45, 137, 122));
    }//GEN-LAST:event_BotonCosMouseEntered

    private void BotonTanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonTanMouseEntered
        BotonTan.setBackground(new Color(45, 137, 122));
    }//GEN-LAST:event_BotonTanMouseEntered

    private void BotonIvaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonIvaMouseEntered
        BotonIva.setBackground(new Color(45, 137, 122));
    }//GEN-LAST:event_BotonIvaMouseEntered

    private void BotonSqrtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonSqrtMouseEntered
        BotonSqrt.setBackground(new Color(45, 137, 122));
    }//GEN-LAST:event_BotonSqrtMouseEntered

    private void BotonPowMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonPowMouseEntered
        BotonPow.setBackground(new Color(45, 137, 122));
    }//GEN-LAST:event_BotonPowMouseEntered

    private void Boton7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Boton7MouseExited
       Boton7.setBackground(new Color(0,153,153));
    }//GEN-LAST:event_Boton7MouseExited

    private void Boton8MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Boton8MouseExited
        Boton8.setBackground(new Color(0,153,153));
    }//GEN-LAST:event_Boton8MouseExited

    private void Boton9MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Boton9MouseExited
        Boton9.setBackground(new Color(0,153,153));
    }//GEN-LAST:event_Boton9MouseExited

    private void BotonDeleteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonDeleteMouseExited
        BotonDelete.setBackground(new Color(0,153,153));
    }//GEN-LAST:event_BotonDeleteMouseExited

    private void BotonClearMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonClearMouseExited
        BotonClear.setBackground(new Color(0,153,153));
    }//GEN-LAST:event_BotonClearMouseExited

    private void BotonSenMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonSenMouseExited
        BotonSen.setBackground(new Color(0,153,153));
    }//GEN-LAST:event_BotonSenMouseExited

    private void BotonIvaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonIvaMouseExited
        BotonIva.setBackground(new Color(0,153,153));
    }//GEN-LAST:event_BotonIvaMouseExited

    private void Boton4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Boton4MouseExited
        Boton4.setBackground(new Color(0,153,153));
    }//GEN-LAST:event_Boton4MouseExited

    private void Boton5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Boton5MouseExited
        Boton5.setBackground(new Color(0,153,153));
    }//GEN-LAST:event_Boton5MouseExited

    private void Boton6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Boton6MouseExited
        Boton6.setBackground(new Color(0,153,153));
    }//GEN-LAST:event_Boton6MouseExited

    private void BotonMenosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonMenosMouseExited
        BotonMenos.setBackground(new Color(0,153,153));
    }//GEN-LAST:event_BotonMenosMouseExited

    private void BotonMultipMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonMultipMouseExited
        BotonMultip.setBackground(new Color(0,153,153));
    }//GEN-LAST:event_BotonMultipMouseExited

    private void BotonCosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonCosMouseExited
        BotonCos.setBackground(new Color(0,153,153));
    }//GEN-LAST:event_BotonCosMouseExited

    private void BotonSqrtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonSqrtMouseExited
        BotonSqrt.setBackground(new Color(0,153,153));
    }//GEN-LAST:event_BotonSqrtMouseExited

    private void Boton1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Boton1MouseExited
        Boton1.setBackground(new Color(0,153,153));
    }//GEN-LAST:event_Boton1MouseExited

    private void Boton2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Boton2MouseExited
        Boton2.setBackground(new Color(0,153,153));
    }//GEN-LAST:event_Boton2MouseExited

    private void Boton3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Boton3MouseExited
        Boton3.setBackground(new Color(0,153,153));
    }//GEN-LAST:event_Boton3MouseExited

    private void BotonMasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonMasMouseExited
        BotonMas.setBackground(new Color(0,153,153));
    }//GEN-LAST:event_BotonMasMouseExited

    private void BotonDivisionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonDivisionMouseExited
        BotonDivision.setBackground(new Color(0,153,153));
    }//GEN-LAST:event_BotonDivisionMouseExited

    private void BotonTanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonTanMouseExited
        BotonTan.setBackground(new Color(0,153,153));
    }//GEN-LAST:event_BotonTanMouseExited

    private void BotonPowMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonPowMouseExited
        BotonPow.setBackground(new Color(0,153,153));
    }//GEN-LAST:event_BotonPowMouseExited

    private void Boton2CerosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Boton2CerosMouseExited
        Boton2Ceros.setBackground(new Color(0,153,153));
    }//GEN-LAST:event_Boton2CerosMouseExited

    private void Boton0MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Boton0MouseExited
       Boton0.setBackground(new Color(0,153,153));
    }//GEN-LAST:event_Boton0MouseExited

    private void PiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PiMouseExited
       Pi.setBackground(new Color(0,153,153));
    }//GEN-LAST:event_PiMouseExited

    private void BotonResultadoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonResultadoMouseExited
        BotonResultado.setBackground(new Color(0,153,153));
    }//GEN-LAST:event_BotonResultadoMouseExited

    
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazCalculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Boton0;
    private javax.swing.JButton Boton1;
    private javax.swing.JButton Boton2;
    private javax.swing.JButton Boton2Ceros;
    private javax.swing.JButton Boton3;
    private javax.swing.JButton Boton4;
    private javax.swing.JButton Boton5;
    private javax.swing.JButton Boton6;
    private javax.swing.JButton Boton7;
    private javax.swing.JButton Boton8;
    private javax.swing.JButton Boton9;
    private javax.swing.JButton BotonClear;
    private javax.swing.JButton BotonCos;
    private javax.swing.JButton BotonDelete;
    private javax.swing.JButton BotonDivision;
    private javax.swing.JButton BotonIva;
    private javax.swing.JButton BotonMas;
    private javax.swing.JButton BotonMenos;
    private javax.swing.JButton BotonMultip;
    private javax.swing.JButton BotonPow;
    private javax.swing.JButton BotonResultado;
    private javax.swing.JButton BotonSen;
    private javax.swing.JButton BotonSqrt;
    private javax.swing.JButton BotonTan;
    private javax.swing.JLabel Pantalla;
    private javax.swing.JButton Pi;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
